// Common MySQL column types — suggestions for the searchable type picker.
// Free text is still allowed (e.g. DECIMAL(12,4), ENUM('a','b')).

export const MYSQL_TYPES = [
  'INT',
  'INT UNSIGNED',
  'TINYINT',
  'TINYINT(1)',
  'SMALLINT',
  'MEDIUMINT',
  'BIGINT',
  'BIGINT UNSIGNED',
  'DECIMAL(10,2)',
  'FLOAT',
  'DOUBLE',
  'BIT',
  'BOOLEAN',
  'VARCHAR(255)',
  'CHAR(1)',
  'TINYTEXT',
  'TEXT',
  'MEDIUMTEXT',
  'LONGTEXT',
  'DATE',
  'DATETIME',
  'TIMESTAMP',
  'TIME',
  'YEAR',
  'JSON',
  'BINARY',
  'VARBINARY(255)',
  'BLOB',
  'LONGBLOB',
  "ENUM('a','b')",
];
